use_frameworks!

platform :ios, '13.0'

target 'DGCChatMessage_Example' do
  pod 'DGCLog', :path => '../../DGCLog'
  pod 'DGCChatMessage', :path => '../'

  target 'DGCChatMessage_Tests' do
    inherit! :search_paths

    
  end
end
